server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratstudy?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasespackage: com.rat.study.dataSource.entity